version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webnet
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gtd
      POSTGRES_USER: gtd
      POSTGRES_PASSWORD: gtd
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  dbdata:
